import unittest
bdLibPath = os.path.abspath(sys.argv[0] + "..")
if not bdLibPath in sys.path: sys.path.append(bdLibPath)
from _lib import *

    
class TilsTests(unittest.TestCase):
    
    def test_001_HomeworkEvaluationDownloadCorrectData_Ilia(self):
       RunBrowserToUrl("chrome","http://stage.telerikacademy.com")
       LoginAsAdmin("myadmin2", "mypassword2")
       NavigateToAdminModule(Admin.homeworkEvaluationLabel)
       click(find(HomeworkEvaluation.courseInput).right().find(HomeworkEvaluation.dropDownArrow))
       click(HomeworkEvaluation.courseSelection)
       click(find(HomeworkEvaluation.lectureInput).right().find(HomeworkEvaluation.dropDownArrow))
       click(HomeworkEvaluation.lectureSelection)
       type(HomeworkEvaluation.userInput,"ivand"+Key.ENTER); sleep(2)
       click(HomeworkEvaluation.exportToExcelButton)
       click(find(HomeworkEvaluation.excelFileChrome))
       wait(HomeworkEvaluation.excelValidadion,10)
       wait(HomeworkEvaluation.excelDataValidation,10)

    def test_100_Edit_BonusPointsEditSuccessId212(self):
        RunBrowserToUrl("iexplore","http://stage.telerikacademy.com/Administration_Courses/UsersInCoursesBonuses");sleep(5)

        wait("velizar_btn_FirstEdit_Bonus.png").highlight(3)
        click("velizar_btn_FirstEdit_Bonus.png"); sleep(2)
        find("velizar_form_BonusEdit2.png").highlight(3)
        find("velizar_label_Points.png").highlight(2)
        click("velizar_label_Points.png")
        type(Key.BACKSPACE*10);sleep(2)
        type(Key.DELETE*10);sleep(2)
        type("7.77");sleep(2)
        type(Key.TAB);sleep(2)
        type(Key.BACKSPACE*100);sleep(2)
        type("EDITED!");sleep(2)
        find("velizar_btn_Update_BonusPoints.png").highlight(2)
        click("velizar_btn_Update_BonusPoints.png"); sleep(2)
        type(Key.F5); sleep(5)
        find("velizar_label_Edited.png").right(1200).highlight(3)
        find("velizar_label_777.png").highlight(3)
        reg = find("velizar_label_Edited.png").right(1200)

        assert reg.exists("velizar_label_777.png")

        #Returning back to start situation
        wait("velizar_btn_FirstEdit_Bonus.png").highlight(3)
        click("velizar_btn_FirstEdit_Bonus.png"); sleep(2)
        find("velizar_label_Points.png").highlight(2)
        click("velizar_label_Points.png")
        type(Key.BACKSPACE*10);sleep(2)
        type(Key.DELETE*10);sleep(2)
        type("6.3")
        type(Key.TAB);sleep(2)
        type(Key.BACKSPACE*100);sleep(2)
        type("Excellent presentation!");sleep(2)
        find("velizar_btn_Update_BonusPoints.png").highlight(2)
        click("velizar_btn_Update_BonusPoints.png"); sleep(2)
        type(Key.F5); sleep(5)

    def test_101_Edit_BonusPointsEditWithAllCoursesId213(self):
        RunBrowserToUrl("iexplore","http://stage.telerikacademy.com/Administration_Courses/UsersInCoursesBonuses");sleep(5)

        wait("velizar_btn_FirstEdit_Bonus.png").highlight(3)
        click("velizar_btn_FirstEdit_Bonus.png"); sleep(2)
        find("velizar_form_BonusEdit.png").highlight(3)
        find("velizar_dropDownArrow_EditingBonusPoins.png").highlight(3)
        click("velizar_dropDownArrow_EditingBonusPoins.png")
        type(Key.DOWN)
        find("velizar_btn_Update_BonusPoints.png").highlight(2)
        click("velizar_btn_Update_BonusPoints.png"); sleep(2)

        assert not exists(Pattern("velizar_form_BonusEdit2.png").similar(0.81))

    def test_101_Edit_BonusPoints(self):
        RunBrowserToUrl("iexplore","http://stage.telerikacademy.com/Administration_Courses/UsersInCoursesBonuses");sleep(5)

        wait("velizar_btn_FirstEdit_Bonus.png").highlight(3)
        click("velizar_btn_FirstEdit_Bonus.png"); sleep(2)
        find("velizar_form_BonusEdit.png").highlight(3)
        find("velizar_dropDownArrow_EditingBonusPoins.png").highlight(3)
        click("velizar_dropDownArrow_EditingBonusPoins.png")
        type(Key.DOWN)
        find("velizar_btn_Update_BonusPoints.png").highlight(2)
        click("velizar_btn_Update_BonusPoints.png"); sleep(2)

        assert not exists(Pattern("velizar_form_BonusEdit.png").similar(0.81))

    def test_200_ImportTeams(self):
         RunBrowserToUrl("firefox", "http://stage.telerikacademy.com/Administration_Teamwork/ImportTeams")
         wait(Tils.academy_logo, 15)
         click(ImportTeamsPage.teamwork_dropdown)
         click(ImportTeamsPage.select_TeamworkP)
         click(ImportTeamsPage.set_number_users); sleep(0.5)
         type(Key.DELETE + Key.NUM8)
         click(ImportTeamsPage.select_teamname); sleep(2)
         wheel(ImportTeamsPage.wheel_target, WHEEL_DOWN, 1)
         wait(ImportTeamsPage.set_teamname, 3)
         click(ImportTeamsPage.set_teamname)
         click(ImportTeamsPage.select_files)
         type(ImportTeamsPage.file_name, "UserWantInTeamwork.xls")
         click(ImportTeamsPage.open_button)
         assert exists(ImportTeamsPage.exist_importedFile)
         click(ImportTeamsPage.column_toSort)
         click(ImportTeamsPage.select_column_toSort)
         click(ImportTeamsPage.import_button)

    def test_201_TryToImportTeamWhitoutSelectingTeamwork_TCId_218(self):
         RunBrowserToUrl("firefox", "http://stage.telerikacademy.com/Administration_Teamwork/ImportTeams")
         wait(Tils.academy_logo, 15)
         click(ImportTeamsPage.set_number_users); sleep(0.5)
         type(Key.DELETE + Key.NUM8)
         click(ImportTeamsPage.select_teamname); sleep(2)
         wheel(ImportTeamsPage.wheel_target, WHEEL_DOWN, 1)
         wait(ImportTeamsPage.set_teamname, 3)
         click(ImportTeamsPage.set_teamname)
         click(ImportTeamsPage.select_files)
         type(ImportTeamsPage.file_name, "UserWantInTeamwork.xls")
         click(ImportTeamsPage.open_button)
         assert exists(ImportTeamsPage.exist_importedFile)
         click(ImportTeamsPage.column_toSort)
         click(ImportTeamsPage.select_column_toSort)
         click(ImportTeamsPage.import_button)
         assert exists(ImportTeamsPage.chose_teamworkMessage)

    def test_202_TryToImportTeamWhitoutSettingNumberOfUsersPerTeam_TCId_219(self):
         RunBrowserToUrl("firefox", "http://stage.telerikacademy.com/Administration_Teamwork/ImportTeams")
         wait(Tils.academy_logo, 15)
         click(ImportTeamsPage.teamwork_dropdown)
         click(ImportTeamsPage.select_TeamworkP)
         click(ImportTeamsPage.select_teamname); sleep(2)
         wheel(ImportTeamsPage.wheel_target, WHEEL_DOWN, 1)
         wait(ImportTeamsPage.set_teamname, 3)
         click(ImportTeamsPage.set_teamname)
         click(ImportTeamsPage.select_files)
         type(ImportTeamsPage.file_name, "UserWantInTeamwork.xls")
         click(ImportTeamsPage.open_button)
         assert exists(ImportTeamsPage.exist_importedFile)
         click(ImportTeamsPage.column_toSort)
         click(ImportTeamsPage.select_column_toSort)
         click(ImportTeamsPage.import_button)
         assert exists(ImportTeamsPage.chose_numberOfUSersMessage)

    def test_203_TryToImportTeamWhitoutSettingTypeOfNames_TCId_220(self):
         RunBrowserToUrl("firefox", "http://stage.telerikacademy.com/Administration_Teamwork/ImportTeams")
         wait(Tils.academy_logo, 15)
         click(ImportTeamsPage.teamwork_dropdown)
         click(ImportTeamsPage.select_TeamworkP)
         click(ImportTeamsPage.set_number_users); sleep(0.5)
         type(Key.DELETE + Key.NUM8)
         click(ImportTeamsPage.select_files)
         type(ImportTeamsPage.file_name, "UserWantInTeamwork.xls")
         click(ImportTeamsPage.open_button)
         assert exists(ImportTeamsPage.exist_importedFile)
         click(ImportTeamsPage.column_toSort)
         click(ImportTeamsPage.select_column_toSort)
         click(ImportTeamsPage.import_button)
         wait(ImportTeamsPage.chose_teamworkNames, 5)
         assert exists(ImportTeamsPage.chose_teamworkNames)

    def test_204_TryToImportTeamWhitoutSelctExcelFile_TCId_221(self):
         RunBrowserToUrl("firefox", "http://stage.telerikacademy.com/Administration_Teamwork/ImportTeams")
         wait(Tils.academy_logo, 15)
         click(ImportTeamsPage.teamwork_dropdown)
         click(ImportTeamsPage.select_TeamworkP)
         click(ImportTeamsPage.set_number_users); sleep(0.5)
         type(Key.DELETE + Key.NUM8)
         click(ImportTeamsPage.select_teamname); sleep(2)
         wheel(ImportTeamsPage.wheel_target, WHEEL_DOWN, 1)
         wait(ImportTeamsPage.set_teamname, 3)
         click(ImportTeamsPage.set_teamname)
         click(ImportTeamsPage.column_toSort)
         click(ImportTeamsPage.select_column_toSort)
         click(ImportTeamsPage.import_button)
         assert exists(ImportTeamsPage.chose_fileToImportMessage)

    def test_205_TryToImportTeamWithInvalidImportedFile(self):
         RunBrowserToUrl("firefox", "http://stage.telerikacademy.com/Administration_Teamwork/ImportTeams")
         wait(Tils.academy_logo, 15)
         click(ImportTeamsPage.teamwork_dropdown)
         click(ImportTeamsPage.select_TeamworkP)
         click(ImportTeamsPage.set_number_users); sleep(0.5)
         type(Key.DELETE + Key.NUM8)
         click(ImportTeamsPage.select_teamname); sleep(2)
         wheel(ImportTeamsPage.wheel_target, WHEEL_DOWN, 1)
         wait(ImportTeamsPage.set_teamname, 3)
         click(ImportTeamsPage.set_teamname)
         click(ImportTeamsPage.select_files)
         type(ImportTeamsPage.file_name, "ImportTeams.png")
         click(ImportTeamsPage.open_button); sleep(0.5)
         click(ImportTeamsPage.column_toSort)
         click(ImportTeamsPage.select_column_toSort)
         click(ImportTeamsPage.import_button)
         assert exists(ImportTeamsPage.invalid_importFileMessage)

    def test_301_HER_Reaction_Available(self):
         HER_helpers.navigateAndOpenGrid()
         ivand = find(HER.label_ivand).highlight(2)
         ivand.left(600).highlight(2).click(HER.button_arrow)
         assert exists (HER.button_all_evals)
         find(HER.button_all_evals).highlight(1)

    def test_302_HER_Reaction_Haters_Accepted(self):
         HER_helpers.navigateAndOpenGrid()
         ivand = find(HER.label_ivand).highlight(2)
         ivand.left(600).highlight(2).click(HER.button_arrow)
         wait(HER.button_accept_evals)
         click(HER.button_accept_evals)
         assert exists (HER.button_accept_evals)
         
    def test_303_HER_Reaction_Haters_Rejected(self):
         HER_helpers.navigateAndOpenGrid()
         ivand = find(HER.label_ivand).highlight(2)
         ivand.left(600).highlight(2).click(HER.button_arrow)
         click(HER.button_reject_evals)
         assert exists (HER.button_accept_evals)
         
    def test_304_HER_Reaction_Hated(self):
         HER_helpers.navigateAndOpenGrid()
         click(HER.label_hated)
         wait(HER.label_ivand)
         ivand = find(HER.label_ivand).highlight(2)
         ivand.left(600).highlight(2).click(HER.button_arrow)
         assert exists (HER.button_all_evals)
         find(HER.button_all_evals).highlight(1)
		
if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(TilsTests)

    outfile = open("report.html", "w")
    runner = HTMLTestRunner.HTMLTestRunner(stream=outfile, title='TilsTests Report')
    runner.run(suite)
    outfile.close()
